Fixed Other Issue with Tag Parsing
- Previous fix caused another error
'
ValueError: cannot copy sequence with size 3 to array axis with
dimension 4
'
so I just manually copied the required tags to the array.